version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: shipment-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      Jwt__SecretKey: "${JWT__SECRETKEY}"
      Jwt__Issuer: "${JWT__ISSUER}"
      Jwt__Audience: "${JWT__AUDIENCE}"
      Jwt__AccessTokenMinutes: "${JWT__ACCESSTOKENMINUTES}"
      Jwt__RefreshTokenDays: "${JWT__REFRESHTOKENDAYS}"
      Resend__ApiKey: "${RESEND__APIKEY}"
      Resend__FromEmail: "${RESEND__FROMEMAIL}"
      Resend__FromName: "${RESEND__FROMNAME}"
      Cors__AllowedOrigins: "${CORS_ALLOWED_ORIGINS}"
      Smtp__Host: "${SMTP__HOST}"
      Smtp__Port: "${SMTP__PORT}"
      Smtp__UseSsl: "${SMTP__USESSL}"
      Smtp__FromEmail: "${SMTP__FROMEMAIL}"
      Smtp__FromName: "${SMTP__FROMNAME}"
      AdminUser__Email: "${ADMINUSER__EMAIL}"
      AdminUser__Password: "${ADMINUSER__PASSWORD}"
      AdminUser__FirstName: "${ADMINUSER__FIRSTNAME}"
      AdminUser__LastName: "${ADMINUSER__LASTNAME}"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:16-alpine
    container_name: shipment-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: shipment-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  mailhog:
    image: mailhog/mailhog
    container_name: shipment-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  postgres_data:
